// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bottle struct {
	// キープボトル
	BottleID   string `json:"bottleId"`
	BottleName string `json:"bottleName"`
}

type BottleListResult struct {
	// キープにできるボトル一覧
	List []*Bottle `json:"list"`
}

type Cast struct {
	// キャスト名
	CastID   string `json:"castId"`
	CastName string `json:"castName"`
}

type Customer struct {
	// お客様の名前
	CustomerID   string `json:"customerId"`
	CustomerName string `json:"customerName"`
}

type IDResult struct {
	// 何かを登録・編集・削除したときには該当レコードのidを返却
	ID string `json:"id"`
}

type NomiNation struct {
	// お客様とキャストの関係
	NomiNationID string `json:"nomiNationId"`
	CustomerID   string `json:"customerId"`
	CastID       string `json:"castId"`
}
