// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Bottle struct {
	// キープボトル
	BottleID   string    `json:"bottleId"`
	BottleName string    `json:"bottleName"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type BottleListResult struct {
	// キープにできるボトル一覧
	List []*Bottle `json:"list"`
}

type Cast struct {
	// キャスト名
	CastID   string `json:"castId"`
	CastName string `json:"castName"`
}

type CastListResult struct {
	List []*Cast `json:"list"`
}

type Customer struct {
	// お客様の名前
	CustomerID   string `json:"customerId"`
	CustomerName string `json:"customerName"`
}

type IDResult struct {
	// 何かを登録・編集・削除したときには該当レコードのidを返却
	ID string `json:"id"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NomiNation struct {
	// お客様とキャストの関係
	NomiNationID string `json:"nomiNationId"`
	CustomerID   string `json:"customerId"`
	CastID       string `json:"castId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
